INSERT INTO tb_product (name, description, price_in_cents, img_url) VALUES ('TV Samsung', 'TV LCD Led Samsung', 400000, 'caminho da imagem');
INSERT INTO tb_product (name, description, price_in_cents, img_url) VALUES ('Smartphone Xiaomi', 'Smartphone Xiaomi Redmi Note 10', 150000, 'caminho_da_imagem');
INSERT INTO tb_product (name, description, price_in_cents, img_url) VALUES ('Notebook Dell', 'Notebook Dell Inspiron 15', 250000, 'caminho_da_imagem');
INSERT INTO tb_product (name, description, price_in_cents, img_url) VALUES ('Fones de Ouvido Sony', 'Fones de Ouvido Bluetooth Sony WH-1000XM4', 30000, 'caminho_da_imagem');
INSERT INTO tb_product (name, description, price_in_cents, img_url) VALUES ('Console Xbox Series X', 'Console Xbox Series X 1TB', 250000, 'caminho_da_imagem');
INSERT INTO tb_product (name, description, price_in_cents, img_url) VALUES ('Cadeira Gamer', 'Cadeira Gamer Ergonômica', 80000, 'caminho_da_imagem');
INSERT INTO tb_product (name, description, price_in_cents, img_url) VALUES ('Monitor LG', 'Monitor LG UltraWide 29"', 120000, 'caminho_da_imagem');
INSERT INTO tb_product (name, description, price_in_cents, img_url) VALUES ('Mouse Gamer', 'Mouse Gamer Logitech G502', 7000, 'caminho_da_imagem');
INSERT INTO tb_product (name, description, price_in_cents, img_url) VALUES ('Teclado Mecânico', 'Teclado Mecânico Redragon Kumara', 15000, 'caminho_da_imagem');
INSERT INTO tb_product (name, description, price_in_cents, img_url) VALUES ('Impressora HP', 'Impressora Multifuncional HP DeskJet 2720', 80000, 'caminho_da_imagem');
INSERT INTO tb_product (name, description, price_in_cents, img_url) VALUES ('Roteador Wi-Fi', 'Roteador Wi-Fi TP-Link Archer C6', 10000, 'caminho_da_imagem');
INSERT INTO tb_product (name, description, price_in_cents, img_url) VALUES ('Caixa de Som Bluetooth', 'Caixa de Som Bluetooth JBL Flip 5', 60000, 'caminho_da_imagem');
INSERT INTO tb_product (name, description, price_in_cents, img_url) VALUES ('Câmera Digital Canon', 'Câmera Digital Canon EOS Rebel T7', 180000, 'caminho_da_imagem');
INSERT INTO tb_product (name, description, price_in_cents, img_url) VALUES ('Ventilador de Teto', 'Ventilador de Teto Arno Ultimate', 50000, 'caminho_da_imagem');
INSERT INTO tb_product (name, description, price_in_cents, img_url) VALUES ('Liquidificador Philips Walita', 'Liquidificador Philips Walita Viva RI2135/91', 30000, 'caminho_da_imagem');
INSERT INTO tb_product (name, description, price_in_cents, img_url) VALUES ('Cafeteira Elétrica', 'Cafeteira Elétrica Britânia CP15', 50000, 'caminho_da_imagem');
INSERT INTO tb_product (name, description, price_in_cents, img_url) VALUES ('Máquina de Lavar Roupa', 'Máquina de Lavar Roupa Brastemp 11kg', 150000, 'caminho_da_imagem');
INSERT INTO tb_product (name, description, price_in_cents, img_url) VALUES ('Aspirador de Pó', 'Aspirador de Pó Electrolux Neo', 80000, 'caminho_da_imagem');
INSERT INTO tb_product (name, description, price_in_cents, img_url) VALUES ('Secador de Cabelo', 'Secador de Cabelo Taiff Black', 60000, 'caminho_da_imagem');
INSERT INTO tb_product (name, description, price_in_cents, img_url) VALUES ('Ferro de Passar', 'Ferro de Passar a Vapor Arno Ultragliss', 40000, 'caminho_da_imagem');
INSERT INTO tb_product (name, description, price_in_cents, img_url) VALUES ('Mochila Escolar', 'Mochila Escolar Infantil com Rodinhas', 70000, 'caminho_da_imagem');